name: Catalogue CI Pipeline
run-name: Catalogue CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - run: echo "golangci-lint run ./..."

  test:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run tests
        run: go test ./...

  integration-test:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run integration tests
        run: go test -tags=integration ./...

  sonar-scan:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run integration tests
        run: make coverage sonar-scan
  ci:
    needs: integration-test
    uses: raghudevopsb89/github-actions/.github/workflows/ci.yml@main
    with:
      component_name: catalogue

