name: Catalogue CI Pipeline
run-name: Catalogue CI Pipeline
on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - run: echo "golangci-lint run ./..."

  test:
    needs: lint
    runs-on: self-hosted
    steps:
      - run: echo "Test Cases"

  ci:
    needs: test
    uses: raghudevopsb89/github-actions/.github/workflows/ci.yml@main
    with:
      component_name: catalogue

